#ifndef KERNEL_NIBBLES_COLORS_H
#define KERNEL_NIBBLES_COLORS_H

#include "kernel/curses.h"

#define BACKGROUND_COLOR         COLOR_BLUE
#define WALL_COLOR               COLOR_LIGHT_RED
#define MESSAGE_BORDER_COLOR     COLOR_WHITE
#define MESSAGE_BACKGROUND_COLOR COLOR_RED
#define MESSAGE_FOREGROUND_COLOR COLOR_WHITE
#define PLAYER_1_COLOR           COLOR_YELLOW
#define PLAYER_2_COLOR           COLOR_LIGHT_MAGENTA
#define PLAYER_3_COLOR           COLOR_GREEN
#define PLAYER_4_COLOR           COLOR_BROWN
#define NUMBER_COLOR             COLOR_YELLOW

#endif /* KERNEL_NIBBLES_COLORS_H */
